import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../providers/Providers";
import Toaster from "@/components/Shared/Toaster/Toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WareSun",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <Providers>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
